version: '3'
services:
  config_service:
    image: challenge/config:latest
    container_name: config-service
    expose:
      - 8762
    ports:
      - 8762:8762 # todo remove, gateway will deal with it
    environment:
      - EUREKA_SERVER=http://registry-service:8761/eureka
  registry_service:
    image: challenge/registry:latest
    container_name: registry-service
    expose:
      - 8761
    ports:
      - 8761:8761 # todo remove, gateway will deal with it
    depends_on:
      - config_service
    environment:
      - CONFIG_SERVER=http://config-service:8762/
  admin_service:
    image: challenge/admin:latest
    container_name: admin-service
    expose:
      - 8763
    ports:
      - 8763:8763 # todo remove, gateway will deal with it
  itinerary_service:
    image: challenge/itinerary:latest
    container_name: itinerary-service
    expose:
      - 8770
    ports:
      - 8770:8770 # todo remove, gateway will deal with it
    depends_on:
      - config_service
      - registry_service
    environment:
      - CONFIG_SERVER=http://config-service:8762/
      - EUREKA_SERVER=http://registry-service:8761/eureka
      - ADMIN_SERVER=http://admin-service:8763/
  search_service:
    image: challenge/search:latest
    container_name: search-service
    expose:
      - 8771
    ports:
      - 8771:8771 # todo remove, gateway will deal with it
    depends_on:
      - config_service
      - registry_service
      - itinerary_service
    environment:
      - CONFIG_SERVER=http://config-service:8762/
      - EUREKA_SERVER=http://registry-service:8761/eureka
      - ADMIN_SERVER=http://admin-service:8763/
      - UAA_SERVER=http://uaa:8090/
#  search_service_2:
#    image: challenge/search:latest
#    container_name: search-service-2
#    expose:
#      - 8771
#    #ports:
#    #  - 8771:8771 # todo remove, gateway will deal with it
#    depends_on:
#      - config_service
#      - registry_service
#      - itinerary_service
#    environment:
#      - CONFIG_SERVER=http://config-service:8762/
#      - EUREKA_SERVER=http://registry-service:8761/eureka
#      - ADMIN_SERVER=http://admin-service:8763/
  gateway_service:
    image: challenge/gateway:latest
    container_name: gateway-service
    ports:
      - 8080:8080
    depends_on:
      - config_service
      - registry_service
    environment:
      - CONFIG_SERVER=http://config-service:8762/
      - EUREKA_SERVER=http://registry-service:8761/eureka
      - ADMIN_SERVER=http://admin-service:8763/
      - UAA_SERVER=http://uaa:8090/
  uaa:
    image: challenge/uaa:latest
    container_name: uaa
    expose:
      - "8090"
    ports:
      - "8090:8090"
