server:
  port: 8760

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: itinerary-service
          uri: lb://itinerary-service
          predicates:
            - Path=/itineraries/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
