server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: itinerary-service
          uri: lb://itinerary-service
          predicates:
            - Path=/api/itineraries/**
          filters:
            - StripPrefix=2
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=2
            - TokenRelay=
            - RemoveRequestHeader=Cookie
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8763}
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: gateway-service
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,resource.read
        provider:
          uaa:
            authorization-uri: ${UAA_SERVER:http://localhost:8090}/uaa/oauth/authorize
            token-uri: ${UAA_SERVER:http://localhost:8090}/uaa/oauth/token
            user-info-uri: ${UAA_SERVER:http://localhost:8090}/uaa/userinfo
            user-name-attribute: sub
            jwk-set-uri: ${UAA_SERVER:http://localhost:8090}/uaa/token_keys

management:
  endpoints:
    web:
      exposure:
        include: '*'

# eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
