server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: itinerary-service-api
          uri: lb://itinerary-service
          predicates:
            - Path=/api/itineraries
          filters:
            - StripPrefix=1
        - id: search-service-api
          uri: lb://search-service
          predicates:
            - Path=/api/search
          filters:
            - StripPrefix=1
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8763}

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
