server:
  port: 8770
  error:
    include-message: always # todo security : remove (default is never)

spring:
  # enabling H2 console at http://localhost:8091/h2-console
  h2:
    console:
      enabled: true
  # database
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  # jpa/hibernate
  jpa:
    show-sql: true # todo security : set to false
    hibernate:
      ddl-auto: update # todo security : change or remove
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true # todo security : set to false
        use_sql_comments: false
        format_sql: false
  # overwriting jackson defaults to unify date serialization among services
  jackson:
    time-zone: UTC
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  descriptions:
    origin:
      value: "example -> 'city_A'"
    departure:
      value: "example -> '10:00'"
    list:
      value: "list the itineraries, using parameters as filters"
      notes: "itineraries may be filtered by departure time or origin city;
                      filters can be used together or individually;
                      if no filter is used, return all the itineraries"
    item-post:
      value: "add an itinerary"
      notes: "WARNING! post requests should not include 'id', 'createdAt' and 'status' attributes"
    item-get:
      value: "get an itinerary"
    item-put:
      value: "update an itinerary"
    item-delete:
      value: "delete an itinerary"
