server:
  port: 8091
  error:
    include-message: always # todo security : remove (default is never)

spring:
  # enabling H2 console at http://localhost:8091/h2-console
  h2:
    console:
      enabled: true
  # database
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
  # jpa/hibernate
  jpa:
    show-sql: true # todo security : set to false
    hibernate:
      ddl-auto: update # todo security : change or remove
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true # todo security : set to false
        use_sql_comments: false
        format_sql: false
  jackson:
    time-zone: UTC
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
