server:
  port: 8761

spring:
  application:
    name: registry-service
#  boot:
#    admin:
#      client:
#        url: ${ADMIN_SERVER:http://localhost:8763} # todo uncomment?

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
