server:
  port: 8771

spring:
  # overwriting jackson defaults to unify date serialization among services
  jackson:
    time-zone: UTC
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"

logging:
  level:
    com:
      challenge: DEBUG

# eureka client
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
    endpoints:
      web:
        exposure:
          include: '*'

# hystrix
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxyStreamAllowList: '*'

#swagger
swagger:
  descriptions:
    byLessTime:
      value: "find paths between two cities ordered by less time spent since departure"
      notes: "example -> destination = 'city_C' and origin = 'city_A'"
    byLessConnections:
      value: "find paths between two cities ordered by less steps done"
      notes: "example -> destination = 'city_C' and origin = 'city_A'"
