server:
  port: 8092
  error:
    include-message: always # todo security : remove (default is never)

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  # overwriting jackson defaults to unify date serialization among services
  jackson:
    time-zone: UTC
    date-format: "yyyy-MM-dd'T'HH:mm:ss'Z'"

feign:
  hystrix:
    enabled: true

management:
    endpoints:
      web:
        exposure:
          include: '*'
